### ISSUE TITLE
Flow on sending transaction on CKB-Axon bridge

### ISSUE THREAD

**Issue by fjchen7** [synapseweb3/relayer#166]
Axon doesn't exactly comply with IBC interfaces. There are two problems we have to solve

1. Make sure the forcelay main flow won't block IBC interaction
2. Transaction sending, mainly on building request.

This issue discusses the second problem. Though we have had some dicsussion before, I still want to put it here for later follow-up and implementation.

## Status quo

The method [send_messages_and_wait_commit](https://github.com/synapseweb3/forcerelay/blob/main/crates/relayer/src/chain/endpoint.rs#L143) in trait `Endpoint` is the only entrance to send transaction. The accepcted parameter is `TrackedMsgs`:

```rust
pub struct TrackedMsgs {
    pub msgs: Vec<Any>,
    pub tracking_id: TrackingId,
}
```

It is a protobuf-encoded data. Hopefully thanks to the unique `tracking_id` we can distinguish what the real type it should be decoded to. The decoded types are various Msg, like [`MsgConnectionOpenTry`](https://github.com/synapseweb3/forcerelay/blob/main/crates/relayer-types/src/core/ics03_connection/msgs/conn_open_try.rs#L29), which is constructed by worker.

```
pub struct MsgConnectionOpenTry {
    pub previous_connection_id: Option<ConnectionId>,
    pub client_id: ClientId,
    pub client_state: Option<Any>,
    pub counterparty: Counterparty,
    pub counterparty_versions: Vec<Version>,
    pub proofs: Proofs,
    pub delay_period: Duration,
    pub signer: Signer,
}
```

[Here](https://github.com/synapseweb3/forcerelay/blob/main/crates/relayer/src/connection.rs#L1051) is how it is constructed in real flow.

### CKB interface

[Here](https://github.com/synapseweb3/ckb-ics/blob/main/axon/src/handler.rs#L165) is an example of IBC interface on CKB contract

```rust
pub fn handle_msg_connection_open_try(
    client: Client,
    old_connections: IbcConnections,
    new_connections: IbcConnections,
    msg: MsgConnectionOpenTry,
) -> Result<(), VerifyError>
```

The most important field in [msg](https://github.com/synapseweb3/ckb-ics/blob/main/axon/src/message.rs#L122) is `proof`, which is a rip-encoded bytes of [ObjectProof](https://github.com/synapseweb3/ckb-ics/blob/main/axon/src/proof.rs#L8) (It is possibly changed in the future)

```rust
pub struct ObjectProof {
    pub tx: Transaction,
    pub tx_root: H256,
    pub tx_proof: Vec<Vec<u8>>,
    pub receipt: TransactionReceipt,
    pub receipt_root: H256,
    pub receipt_proof: Vec<Vec<u8>>,
    pub idx: u64,
    pub block: Block,
}
```

## Building request

The main flow constructs Msg with the help of query methods provided by CKB endpoint. [Here](https://github.com/synapseweb3/forcerelay/blob/main/crates/relayer/src/connection.rs#L956) is an example.

Consideration

- We can't depend on the main flow to get data we need as it is hard to implement all query methods semantically on CKB endpoint. Before calling `send_messages_and_wait_commit` we may just get a **MOCK** msg parameter and the real request should be constructed all over again in this method. The main issue here is to **avoid main flow blocking our logic**.
- Old status (e.g. `old_connection`) are stored in witness of IBC cell onchain. We can **get all IBC cell** at first and check if it is needed after **deserializing witness**.
- Proof: if we have the transaction hash then it is possibly to get the corresponding transaction, receipt and block by RPC. But the feasibility should be checked as the needed fields are too complicated and too many.

No idea

- How to build new status (e.g. `new_connection`)? Though these types have the same fields with IBC types, but it seems we won't verify all. **Which is needed, which just acts like placeholder**?

## Security

- [ ] How to link data and proof? That is, how to make sure that: 

  1. The receipt is for the corresponding IBC transaction on counterparty chain.
  2. The block indeed contains the IBC transaction

- [ ] `client` is the Axon client status for proof. But CKB contract caller provides both `client` and transaction proof. It seems like a man verify itself.
  - Solution: verify that submitted `client` is on CKB chain.

**Comment by ashuralyk** [comment]
> client is the Axon client status for proof. But CKB contract caller provides both client and transaction proof. It seems like a man verify itself

don't forget we have axon light-client on CKB chain which is used to check the BLS signature in one Axon's block, so the problem is we indeed provide the block itself but we DO NOT verify it only using the data from block, we also use on-chain light-client to verify which we can trust and maintained by Axon chain

**Comment by ashuralyk** [comment]
> How to build new status (e.g. new_connection)? Though these types have the same fields with IBC types, but it seems we won't verify all. Which is needed, which just acts like placeholder?

not yet, we can verify all of those fields in the object like the Connection, in original IBC protocol, Connection object is written in the consensus-state-root, so the counterparty can build a new Connection according to its knowledgement, but in Axon we can't do that, we should firstly verify the existence of ibc transaction and then check out its event parameters which contain a expected Connection object, and back to the CKB, we can verify those two Connection objects in the contract which one is in new_connection msg and another one is in event parameters
