### ISSUE TITLE
Missing finality update caching in `get_finality_updates_from`

### ISSUE THREAD

**Issue by whfuyn** [synapseweb3/relayer#177]
https://github.com/synapseweb3/forcerelay/blob/afc197085d32be5aa1dbb243b3ccac1a992e1417/crates/relayer/src/light_client/eth.rs#L717-L761

It appears that we are returning fetched updates immediately when the number of fetched updates is less than expected, but in this case, we're not caching these updates as we would if we exited the loop.

https://github.com/synapseweb3/forcerelay/blob/afc197085d32be5aa1dbb243b3ccac1a992e1417/crates/relayer/src/light_client/eth.rs#L739-L742

**Comment by ashuralyk** [comment]
That's indeed a bug but won't make a big hurt on us in a normal case, so glad you dig it bro
