### ISSUE TITLE
[Optimization] Do not write the transaction of the genesis block to death, this tx can be found in the genesis block, change it to load from genesis from mainnet, testnet and dev

### ISSUE THREAD

**Issue by 15168316096** [synapseweb3/relayer#191]
## Summary of Bug
 Do not write the transaction of the genesis block to death, this tx can be found in the genesis block, change it to load from genesis from mainnet, testnet and dev

## Version

- forcerelayer git commit:afc197085d32be5aa1dbb243b3ccac1a992e1417
- ibc-contract git commit:feat: support the Capella fork

## Steps to Reproduce

- configure ckb dev node
- start relayer

## Track 

- log info

2023-05-18T04:59:32.370549Z ERROR ThreadId(30) unexpected error: 
0: send_tx resulted in chain error event: 

         0: RPC client returns error response: Failure { jsonrpc: Some(V2), error: Error { code: ServerError(-301), message: "TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x29ed5663501cd171513155f8939ad2c9ffeb92aa4879d39cde987f8eb627440700000000))", data: Some(String("Resolve(Unknown(OutPoint(0x29ed5663501cd171513155f8939ad2c9ffeb92aa4879d39cde987f8eb627440700000000)))")) }, id: Num(33) }

- callstack：https://github.com/synapseweb3/forcerelay/blob/f9a65ad49d77a4e96fd064cbb79c8225bbeea644/crates/relayer/src/chain/ckb/helper.rs#L185

**Comment by Xcodes-chain** [comment]
@whfuyn fu

**Comment by whfuyn** [comment]
https://github.com/synapseweb3/forcerelay/pull/189
Could you please give this PR a try and let me know if it resolves the issue?
