### ISSUE TITLE
[document]A complete forcerelay operation document

### ISSUE THREAD

**Issue by 15168316096** [synapseweb3/relayer#285]
A complete forcerelay operation document, can be found in Hermes (IBC CLI) document, supplemented related documentation, related documentation Link: https://hermes.informal.systems/documentation/commands/path-setup/clients.html

**Comment by ashuralyk** [comment]
confirmed

**Comment by ashuralyk** [comment]
to clarify this, I need what is supposed to do in detail under your need by following this documentation? please give some particular scenarios.

**Comment by Flouse** [comment]
> to clarify this, I need what is supposed to do in detail under your need by following this documentation? please give some particular scenarios.

## How to run a new Forcerelay/Axon relayer as a third party?
Operation instructions that shows
- How to setup forcerelay
- How to deploy related Solidity contract
- How to deploy related CKB contracts

Provide the latest docs links and some handy scripts if necessary

**Comment by ashuralyk** [comment]
https://www.notion.so/cryptape/Forcerelay-Axon-a12ae348481d4c52b011d53ea1c1e69a
