### ISSUE TITLE
Fully implement CKB chain endpoint

### ISSUE THREAD

**Issue by jjyr** [synapseweb3/relayer#316]
## Summary

The `supervisor` module in ibc-tests invoke some unimplemented CKB chain endpoint interface. We should fully support these interfaces.

See errors log in this CI. (The CI is successed because the `supervisor` module do not interrupt the execution even errors raised).

https://github.com/synapseweb3/forcerelay/actions/runs/5990108146/job/16247059515?pr=308

``` bash
2023-08-27T09:36:26.601586Z ERROR scan.chain{chain=ckb4ibc-0}:scan.client{client=7ede7d98985de2f464e737b8e177ede186c50d3d584d1bd9b2399330c2187e61}:scan.connection{connection=7ede7d-connection-0}: ibc_relayer::supervisor::scan: error fetching counterparty connection state: failed to query counterparty connection state of connection '7ede7d-connection-0' on counterparty chain 'ckb4ibc-0', reason: relayer error

Caused by:
    Cannot convert 7ede7d-connection-1 as a ckb conn id

Location:
    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9

Location:
    /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9
```

## Problem Definition

We have some unimplemented interface in CKB chain endpoint.

### Dependencies

- [ ] CKB light client: chain query / proof verification / health check.

## Proposal

Fully implement the CKB chain endpoint.

## Acceptance Criteria

The supervisor module shouldn't output any error logs.

**Comment by ashuralyk** [comment]
I think this error is ok, because there is indeed no `7ede7d-connection-1` connection in `ckb4ibc-0`

**Comment by jjyr** [comment]
The unimplemented interfaces are mostly related to light clients https://github.com/synapseweb3/forcerelay/issues/265

**Comment by ashuralyk** [comment]
@jjyr I rarely find problem from this issue happened so far, this issue can be closed?

**Comment by ashuralyk** [comment]
@jjyr @Flouse I guess this Issue can close
