### ISSUE TITLE
Fix `fn update_subscribe` in crates/relayer/src/chain/axon/monitor.rs

### ISSUE THREAD

**Issue by Flouse** [synapseweb3/relayer#335]
https://github.com/synapseweb3/forcerelay/blob/7d2779599ac44af08cb002bdd80412678fffd6b7/crates/relayer/src/chain/axon/monitor.rs#L138-L155

When the sender end is closed, this will always return `Continue`? (I guess the sender is supposed to send `Shutdown` before dropping, but we can have more robust error handling here, and `AxonChain` is not actually doing this.)

_Originally posted by @blckngm in https://github.com/synapseweb3/forcerelay/pull/271#discussion_r1281374385_

**Comment by blckngm** [comment]
Fixed.
