### ISSUE TITLE
st-packet-test: thread 'main' panicked at examples/sudt-transfer.rs:789:39

### ISSUE THREAD

**Issue by Flouse** [synapseweb3/relayer#370]
## Steps to Reproduce
See https://github.com/synapseweb3/forcerelay/actions/runs/6760631288/job/18374632265#step:13:25

### Attach logs here if you have them

```js
sent transaction 6a5c8f48dd1e121d8dbcbef7ace2d075b5d53c036cdc8aed05e34e403adbc822
thread 'main' panicked at examples/sudt-transfer.rs:789:39:
rejected
```
____

## For Admin Use

- [x] Appropriate labels applied
- [x] Appropriate contributors tagged

**Comment by blckngm** [comment]
The transaction seems to be confirmed later: https://pudge.explorer.nervos.org/transaction/0x6a5c8f48dd1e121d8dbcbef7ace2d075b5d53c036cdc8aed05e34e403adbc822

It's more likely a ckb mempool/RPC issue and not a bug in sudt-transfer cli.

I'll improve the error reporting a bit.

**Comment by blckngm** [comment]
* https://github.com/synapseweb3/forcerelay-ckb-sdk/pull/29
