### ISSUE TITLE
IBC Cell conflict of relayer and `forcerelay-ckb-sdk` generating tx at the same time

### ISSUE THREAD

**Issue by ashuralyk** [synapseweb3/relayer#373]
## Summary of Bug
since channel cell and packet cell only exist one instance in CKB, and also due to forcerelay and `forcerelay-ckb-sdk` work independently, so that cell compete happened while both of them generate transaction that consumes a same cell at the same time

I guess to regenerate transaction may solve this problem

**Comment by blckngm** [comment]
The relayer needs to retry, generating a new tx using new cells. Maybe it's already handled by the framework (hermes)?

It's a nice to have for the cli. Users can always retry manually.

**Comment by ashuralyk** [comment]
> The relayer needs to retry, generating a new tx using new cells. Maybe it's already handled by the framework (hermes)?
> 
> It's a nice to have for the cli. Users can always retry manually.

actually, I don't see any concerns about this issue in Hermes, and it doesn't retry sending transaction in the deployed instance
